# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, v2.x ]
  pull_request:
    branches: [ master, v2.x ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    
    container:
      image: ubuntu:20.04
      options: --user root --cpus 2

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: apt update && apt install -y wget curl gnupg make
    - run: cp .github/workflows/nginx.list /etc/apt/sources.list.d/nginx.list
    - run: wget http://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key
    - run: apt update -y && apt remove -y nginx nginx-common nginx-full nginx-core 
    - run: apt-get install -y nginx openjdk-11-jdk
    - run: chown root:root `which nginx`
    #- run: curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
    #- run: bash /tmp/nodesource_setup.sh
    #- run: apt-get install -y nodejs
    - run: node -v && java -version
    - run: npm install -g codecov
    - run: which nginx && nginx -v
    - run: make codecov
    - run: codecov
